apiVersion: 'metadata-service.resource.api.sap/v6alpha1'
type: 'MetadataType'
metadata:
  name: 'package'
  path: '/sap/core/ucl/metadata/ord/v1'
  labels: {}
spec:
  typeName: 'Package'
  key:
    - 'id'
  visibility: 'public'
  embedded: false
  description: "A [**Package**](../concepts/grouping-and-bundling#package) organizes a set of related resources together, by publishing and catalog presentation concerns.\n\nThe Package can also be used to indicate which products or vendors provided the packaged resources.\nFor partner or customer content, the Package can indicate this via the `vendor` and `partOfProducts` assignments.\nIn any case, the Package `ordID` namespace MUST reflect the namespace of the providing application (which hosts the resource), not the resource definition owner, which could be a customer or partner.\n\nA Package SHOULD contain at least one resource. Avoid empty Packages.\n\nThe Package assignment of a resource MAY change, so consumers MUST not rely on this to be stable.\n\nA Package does not have a `visibility` property.\nWhether it is displayed is decided by the fact, whether it contains any visible resources according to the visibility role of the aggregator.\n\nTo learn more about the concept and further guidance, see [Package](../concepts/grouping-and-bundling#package)."
  metadataProperties:
    - name: 'id'
      type: 'guid'
      mandatory: true
      unique: true
      description: 'UMS ID (globally unique), used for relations.'
    - name: 'ordId'
      type: 'string'
      description: "The ORD ID is a stable, globally unique ID for ORD resources or taxonomy.\n\nIt MUST be a valid [ORD ID](../index.md#ord-id) of the appropriate ORD type."
      mandatory: true
      constraints:
        maxLength: 255
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):(package):([a-zA-Z0-9._\-]+):(v0|v[1-9][0-9]*)$'
    - name: 'localId'
      type: 'string'
      description: "The locally unique ID under which this resource can be looked up / resolved in the described system itself.\nUnlike the ORD ID it's not globally unique, but it may be useful to document the original ID / technical name.\n\nIt MAY also be used as the `<resourceName>` fragment in the ORD ID, IF it can fulfill the charset and length limitations within the ORD ID.\nBut since this is not always possible, no assumptions MUST be made about the local ID being the same as the `<resourceName>` fragment in the ORD ID."
      constraints:
        maxLength: 255
    - name: 'title'
      type: 'string'
      description: "Human-readable title.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks."
      mandatory: true
      constraints:
        minLength: 1
        maxLength: 255
    - name: 'shortDescription'
      type: 'string'
      description: "Plain text short description.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks."
      mandatory: true
      constraints:
        minLength: 1
        maxLength: 255
    - name: 'description'
      type: 'string'
      description: "Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nThe description SHOULD not be excessive in length and is not meant to provide full documentation.\nDetailed documentation SHOULD be attached as (typed) links."
      mandatory: true
      constraints:
        minLength: 1
    - name: 'version'
      type: 'string'
      description: "The complete [SemVer](https://semver.org/) version string.\n\nIt MUST follow the [Semantic Versioning 2.0.0](https://semver.org/) standard.\nIt SHOULD be changed if the ORD information or referenced resource definitions changed.\nIt SHOULD express minor and patch changes that don't lead to incompatible changes.\n\nWhen the `version` major version changes, the [ORD ID](../index.md#ord-id) `<majorVersion>` fragment MUST be updated to be identical.\nIn case that a resource definition file also contains a version number (e.g. [OpenAPI `info`.`version`](https://spec.openapis.org/oas/v3.1.1.html#info-object)), it MUST be equal with the resource `version` to avoid inconsistencies.\n\nIf the resource has been extended by the user, the change MUST be indicated via `lastUpdate`.\nThe `version` MUST not be bumped for changes in extensions.\n\nThe general [Version and Lifecycle](../index.md#version-and-lifecycle) flow MUST be followed.\n\nNote: A change is only relevant for a version increment, if it affects the ORD resource or ORD taxonomy directly.\nFor example: If a resource within a `Package` changes, but the Package itself did not, the Package version does not need to be incremented."
      mandatory: true
      constraints:
        pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
    - name: 'policyLevel'
      type: 'string'
      description: "The [policy level](../../spec-extensions/policy-levels/) (aka. compliance level) that the described resources need to be compliant with.\nDepending on the chosen policy level, additional expectations and validations rules will be applied.\n\nThe policy level can be defined on ORD Document level, but also be overwritten on an individual package or resource level.\n"
    - name: 'customPolicyLevel'
      type: 'string'
      description: "If the fixed `policyLevel` values need to be extended, an arbitrary `customPolicyLevel` can be provided.\nThe policy level is inherited from packages to resources they contain, but can be overwritten at resource level.\n\nMUST only be provided if `policyLevel` is set to `custom`.\nMUST be a valid [Specification ID](../index.md#specification-id)."
      constraints:
        maxLength: 255
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):([a-zA-Z0-9._\-]+):(v0|v[1-9][0-9]*)$'
    - name: 'policyLevels'
      type: 'string'
      array: true
      description: "A list of [policy levels](../../spec-extensions/policy-levels/) that the described resources need to be compliant with.\nFor each chosen policy level, additional expectations and validations rules will be applied.\n\nPolicy levels can be defined on ORD Document level, but also be overwritten on an individual package or resource level.\n\nA policy level MUST be a valid [Specification ID](../index.md#specification-id)."
    - name: 'packageLinks'
      type: 'custom'
      customTypeName: 'PackageLink'
      array: true
      description: 'Links with semantic meaning that are specific to Packages.'
    - name: 'links'
      type: 'custom'
      customTypeName: 'Link'
      array: true
      description: "Generic links with arbitrary meaning and content.\n\n`packageLinks` MUST be preferred if applicable."
    - name: 'licenseType'
      type: 'string'
      description: "Standardized identifier for the license.\nIt MUST conform to the [SPDX License List](https://spdx.org/licenses)."
      constraints:
        minLength: 1
    - name: 'supportInfo'
      type: 'string'
      description: "Optional information that should be provided when creating a support ticket for the resources bundled in this Package.\nThis can for example be a \"component\" name that needs to be chosen in the support portal.\n\nNotated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nPlease also note that if you want to provide link(s) where you can find support information,\nyou can use `packageLinks` with a link of type `support`."
      constraints:
        minLength: 1
    - name: 'vendor_ID'
      type: 'guid'
      description: "Vendor / organization that is the creator (or responsible party) of the resources that are part of the `Package`.\n\nMUST be a valid reference to a [Vendor](#vendor) ORD ID.\n\nMUST be set to `customer:vendor:Customer:` if the contents of the Package are created by the customer / user.\n\nMUST be set to a registered partner vendor, if the contents of the Package are created by a partner / third party."
      mandatory: true
      constraints:
        maxLength: 256
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):(vendor):([a-zA-Z0-9._\-]+):()$'
    - name: 'partOfProducts_ID'
      type: 'guid'
      array: true
      description: "List of products the resources of the Package are a part of.\n\nMUST be a valid reference to a [Product](#product) ORD ID.\n\n`partOfProducts` that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'countries'
      type: 'string'
      array: true
      description: "List of countries that the Package resources are applicable to.\n\nMUST be expressed as an array of country codes according to [IES ISO-3166 ALPHA-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).\n\n`countries` that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'lineOfBusiness'
      type: 'string'
      array: true
      description: "List of line of business tags.\nNo special characters are allowed except `-`, `_`, `.`, `/` and ` `.\n\n`lineOfBusiness` that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'industry'
      type: 'string'
      array: true
      description: "List of industry tags.\nNo special characters are allowed except `-`, `_`, `.`, `/` and ` `.\n\n`industry` that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'runtimeRestriction'
      type: 'string'
      description: "If provided, all resources that are part of this Package can only run on the listed runtime.\n\nMUST be a valid [system namespace](../index.md#system-namespace)."
      constraints:
        pattern: '^[a-z0-9]+(?:[.][a-z0-9]+){1}$'
    - name: 'tags'
      type: 'string'
      array: true
      description: "List of free text style tags.\nNo special characters are allowed except `-`, `_`, `.`, `/` and ` `.\n\nTags that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'labels'
      type: 'custom'
      customTypeName: 'Labels'
      description: 'Generic labels that can be applied to most ORD information.'
    - name: 'documentationLabels'
      type: 'custom'
      customTypeName: 'DocumentationLabels'
      description: 'Generic documentation labels that can be applied to most ORD information.'
  customTypeDefinitions:
    - name: 'PackageLink'
      metadataProperties:
        - name: 'type'
          type: 'string'
          mandatory: true
        - name: 'customType'
          type: 'string'
          description: "If the fixed `type` enum values need to be extended, an arbitrary `customType` can be provided.\n\nMUST be a valid [Specification ID](../index.md#specification-id).\n\nMUST only be provided if `type` is set to `custom`."
          constraints:
            maxLength: 255
            pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):([a-zA-Z0-9._\-]+):(v0|v[1-9][0-9]*)$'
        - name: 'url'
          type: 'string'
          description: "[URL](https://tools.ietf.org/html/rfc3986) to the PackageLink.\n\nThe link target MUST be absolute and SHOULD be openly accessible."
          mandatory: true
    - name: 'Link'
      metadataProperties:
        - name: 'title'
          type: 'string'
          description: "Human readable title of the link.\n\nMUST be unique within the collection of links provided."
          mandatory: true
          constraints:
            minLength: 1
        - name: 'url'
          type: 'string'
          description: "[URL](https://tools.ietf.org/html/rfc3986) of the link.\n\nThe link target MUST be absolute and SHOULD be openly accessible."
          mandatory: true
        - name: 'description'
          type: 'string'
          description: 'Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown)'
          constraints:
            minLength: 1
    - name: 'Labels'
      metadataProperties:
        - name: 'key'
          type: 'string'
        - name: 'value'
          type: 'string'
    - name: 'DocumentationLabels'
      metadataProperties:
        - name: 'key'
          type: 'string'
        - name: 'value'
          type: 'string'
  metadataRelations:
    - propertyName: 'vendor'
      relatedTypeName: 'Vendor'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      propertyBased: true
      managedByProperty: 'vendor_ID'
      description: "Vendor / organization that is the creator (or responsible party) of the resources that are part of the `Package`.\n\nMUST be a valid reference to a [Vendor](#vendor) ORD ID.\n\nMUST be set to `customer:vendor:Customer:` if the contents of the Package are created by the customer / user.\n\nMUST be set to a registered partner vendor, if the contents of the Package are created by a partner / third party."
      mandatory: true
    - propertyName: 'partOfProducts'
      relatedTypeName: 'Product'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      propertyBased: true
      managedByProperty: 'partOfProducts_ID'
      description: "List of products the resources of the Package are a part of.\n\nMUST be a valid reference to a [Product](#product) ORD ID.\n\n`partOfProducts` that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - propertyName: 'apiResources'
      relatedTypeName: 'ApiResource'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The API resources that are part the given Package.'
      mandatory: false
    - propertyName: 'eventResources'
      relatedTypeName: 'EventResource'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The event resources that are part the given Package.'
      mandatory: false
    - propertyName: 'entityTypes'
      relatedTypeName: 'EntityType'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The entity types that are part the given Package.'
      mandatory: false
    - propertyName: 'dataProducts'
      relatedTypeName: 'DataProduct'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The data products that are part the given Package.'
      mandatory: false
    - propertyName: 'agents'
      relatedTypeName: 'Agent'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The agents that are part the given Package.'
      mandatory: false
    - propertyName: 'capabilities'
      relatedTypeName: 'Capability'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The capabilities that are part the given Package.'
      mandatory: false
    - propertyName: 'integrationDependencies'
      relatedTypeName: 'IntegrationDependency'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      description: 'The integration dependencies that are part the given Package.'
      mandatory: false
