# Lefthook configuration to ensure code generation runs before commit
# Runs `npm run generate` and re-stages any changed files so they are included
# in the current commit.

pre-commit:
  parallel: false
  commands:
    generate:
      run: npm run generate
      stage_fixed: true
      # If generation fails, the commit is blocked.
      # `stage_fixed: true` will re-stage any updated files.
    git_add_generated:
      run: git add src/generated/ docs/spec-v1/interfaces/ docs/spec-v1/examples/ docs/spec-v1/diagrams/ static/spec-v1/interfaces/
      # Stage only the generated TypeScript types and copied documentation/schema files.
