// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  specV1Sidebar: [
    {
      type: "category",
      label: "ORD Specification",
      link: { type: "doc", id: "spec-v1/index" },
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Concepts",
          link: { type: "doc", id: "spec-v1/concepts/index" },
          collapsible: false,
          collapsed: false,
          items: [
            "spec-v1/concepts/identifiers",
            "spec-v1/concepts/versioning-and-lifecycle",
            "spec-v1/concepts/grouping-and-bundling",
            "spec-v1/concepts/system-landscape-model",
            "spec-v1/concepts/perspectives",
            "spec-v1/concepts/data-product",
            "spec-v1/concepts/integration-dependency",
            "spec-v1/concepts/ai-agents-and-protocols",
            "spec-v1/concepts/shared-resources",
          ],
        },
        {
          type: "category",
          label: "Interfaces and Schemas",
          link: { type: "doc", id: "spec-v1/interfaces/index" },
          collapsible: false,
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "spec-v1/interfaces/Configuration",
              label: "ORD Configuration Interface",
            },
            {
              type: "doc",
              id: "spec-v1/interfaces/Document",
              label: "ORD Document Interface",
            },
            {
              type: "doc",
              id: "spec-v1/interfaces/OrdOverlay",
              label: "ORD Overlay Interface",
            },
            "spec-v1/interfaces/document-api",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      className: "sidebar-guides",
      link: { type: "doc", id: "spec-v1/guides/index" },
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "spec-v1/guides/implementing-ord-natively",
          label: "Native Implementation",
        },
      ],
    },
    {
      type: "category",
      label: "Example Files",
      link: { type: "doc", id: "spec-v1/examples/index" },
      collapsed: true,
      items: [
        "spec-v1/examples/configuration-1",
        "spec-v1/examples/document-1",
        "spec-v1/examples/document-agents",
        "spec-v1/examples/document-data-product",
        "spec-v1/examples/document-entity-types",
        "spec-v1/examples/document-integration-dependencies",
        "spec-v1/examples/document-overlays",
        "spec-v1/examples/document-poc",
        "spec-v1/examples/document-special-protocols",
      ],
    },
  ],
  specExtensionsSidebar: [
    { type: "autogenerated", dirName: "spec-extensions" },
  ],
  helpSidebar: [{ type: "autogenerated", dirName: "help" }],
};

module.exports = sidebars;
