apiVersion: 'metadata-service.resource.api.sap/v6alpha1'
type: 'MetadataType'
metadata:
  name: 'product'
  path: '/sap/core/ucl/metadata/ord/v1'
  labels: {}
spec:
  typeName: 'Product'
  key:
    - 'id'
  visibility: 'public'
  embedded: false
  description: "A **product** in ORD is understood as a commercial product or service.\n\nIt is a high-level entity for structuring the software portfolio from a sales / software logistics perspective.\nWhile **system type** is a technical concept, **product** covers the commercial and marketing view.\n\nPlease note that the ORD concept of a product is very simple on purpose.\nThere is no distinction between products and services and concepts like product versions, variants, etc.\n\nORD assumes that this is handled by specialized systems and that ORD only provides the means to correlate to them."
  metadataProperties:
    - name: 'id'
      type: 'guid'
      mandatory: true
      unique: true
      description: 'UMS ID (globally unique), used for relations.'
    - name: 'ordId'
      type: 'string'
      description: "The ORD ID is a stable, globally unique ID for ORD resources or taxonomy.\n\nIt MUST be a valid [ORD ID](../index.md#ord-id) of the appropriate ORD type."
      mandatory: true
      constraints:
        maxLength: 255
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):(product):([a-zA-Z0-9._\-]+):()$'
    - name: 'correlationIds'
      type: 'string'
      array: true
      description: "Correlation IDs can be used to create a reference to related data in other repositories (especially to the system of record).\n\nThey express an \"identity\" / \"equals\" / \"mappable\" relationship to the target ID.\n\nIf a \"part of\" relationship needs to be expressed, use the `partOfGroups` assignment instead.\n\nMUST be a valid [Correlation ID](../index.md#correlation-id)."
    - name: 'title'
      type: 'string'
      description: "Human-readable title.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks."
      mandatory: true
      constraints:
        minLength: 1
        maxLength: 255
    - name: 'shortDescription'
      type: 'string'
      description: "Plain text short description.\n\nMUST NOT exceed 255 chars.\nMUST NOT contain line breaks."
      mandatory: true
      constraints:
        minLength: 1
        maxLength: 255
    - name: 'description'
      type: 'string'
      description: "Full description, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).\n\nThe description SHOULD not be excessive in length and is not meant to provide full documentation.\nDetailed documentation SHOULD be attached as (typed) links."
      constraints:
        minLength: 1
    - name: 'vendor_ID'
      type: 'guid'
      description: "Vendor / organization that is responsible for the Product.\n\nMUST be a valid reference to a [Vendor](#vendor) ORD ID."
      mandatory: true
      constraints:
        maxLength: 256
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):(vendor):([a-zA-Z0-9._\-]+):()$'
    - name: 'parent_ID'
      type: 'guid'
      description: "Optional product parent ORD ID, if a hierarchical product structure needs to be expressed.\n\nMUST be a valid reference to a [Product](#product) ORD ID."
      constraints:
        pattern: '^([a-z0-9]+(?:[.][a-z0-9]+)*):(product):([a-zA-Z0-9._\-]+):()$'
    - name: 'tags'
      type: 'string'
      array: true
      description: "List of free text style tags.\nNo special characters are allowed except `-`, `_`, `.`, `/` and ` `.\n\nTags that are assigned to a `Package` are inherited to all of the ORD resources it contains."
    - name: 'labels'
      type: 'custom'
      customTypeName: 'Labels'
      description: 'Generic labels that can be applied to most ORD information.'
    - name: 'documentationLabels'
      type: 'custom'
      customTypeName: 'DocumentationLabels'
      description: 'Generic documentation labels that can be applied to most ORD information.'
  customTypeDefinitions:
    - name: 'Labels'
      metadataProperties:
        - name: 'key'
          type: 'string'
        - name: 'value'
          type: 'string'
    - name: 'DocumentationLabels'
      metadataProperties:
        - name: 'key'
          type: 'string'
        - name: 'value'
          type: 'string'
  metadataRelations:
    - propertyName: 'vendor'
      relatedTypeName: 'Vendor'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      propertyBased: true
      managedByProperty: 'vendor_ID'
      description: "Vendor / organization that is responsible for the Product.\n\nMUST be a valid reference to a [Vendor](#vendor) ORD ID."
      mandatory: true
    - propertyName: 'parent'
      relatedTypeName: 'Product'
      relatedTypeNamespace: '/sap/core/ucl/metadata/ord/v1'
      propertyBased: true
      managedByProperty: 'parent_ID'
      description: "Optional product parent ORD ID, if a hierarchical product structure needs to be expressed.\n\nMUST be a valid reference to a [Product](#product) ORD ID."
