name: PR Preview (worker)

on:
  workflow_run:
    workflows: ["PR Preview"]
    types: [completed]

jobs:
  pr-preview-fork-deploy:
    permissions:
      contents: read
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: PR preview (worker)
        uses: open-resource-discovery/pr-preview-action@2abf52396925f6bb4d0a82e27bd6f060260d09ae # main
        with:
          token: ${{ secrets.PR_PREVIEW_TOKEN }}
